#!/usr/bin/env php
<?php

namespace PHPDataGen;
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

trait DataClassTrait {
    use ClassTrait;
}

$app = new \Symfony\Component\Console\Application('PHP-DataGen', 'migrate-to-php-parser-dev');
$app->add(new \PHPDataGen\Command\Compile());
$app->add(new \PHPDataGen\Command\Build());

// TODO Config command

$app->run();
