#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('PHP-DataGen', '0.2-alpha');
$app->add(new PHPDataGen\Command\CompileCommand());
$app->add(new PHPDataGen\Command\BuildCommand());

// TODO Config command

$app->run();
